import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Play, RotateCw, Save, Sparkles, Users } from "lucide-react";

import { backgroundsQueryKey, listBackgrounds } from "../../entities/background/repository";
import { charactersQueryKey, listCharacters } from "../../entities/character/repository";
import { effectsQueryKey, listEffects } from "../../entities/effect/repository";
import {
  chatQueryKey,
  getChatSnapshot,
  installMissingRuntimeDependency,
  launchChat,
} from "../../entities/chat/repository";
import { useChatRuntimeClosing } from "../../entities/chat/runtimeState";
import { configQueryKey, getAppConfig, saveSystemConfig } from "../../entities/config/repository";
import {
  generateTemplate,
  getTemplateSession,
  listTemplates,
  saveTemplate,
  saveTemplateSession,
  templatesQueryKey,
  type TemplateSummary,
} from "../../entities/template/repository";
import { TRANSPARENT_BACKGROUND_NAME } from "../../shared/constants";
import { showChatSurface } from "../../shared/desktop/chatWindow";
import { useI18n } from "../../shared/i18n";
import type { ChatSnapshot, TemplateLaunchSession } from "../../shared/platform/types";
import {
  AlertDialog,
  AsyncButton,
  Button,
  EmptyState,
  FilePicker,
  NumberInput,
  QueryErrorState,
  Select,
  Switch,
  TextArea,
  TextInput,
  useToast,
} from "../../shared/ui";
import {
  buildChatLaunchPayload,
  buildDefaultTemplateScenario,
  buildTemplateGenerateInput,
  buildTemplateLaunchSession,
  buildTemplateSummary,
  composeTemplateContent,
  createTemplateDraft,
  getCharacterChipStyle,
  normalizeTemplateSummary,
  templateVoiceLanguages,
} from "./templateFlow";
import "./TemplateEditorPage.css";

const voiceLanguages = templateVoiceLanguages;

export function TemplateEditorPage() {
  const queryClient = useQueryClient();
  const { showToast } = useToast();
  const { t } = useI18n();
  const templatesQuery = useQuery({ queryFn: listTemplates, queryKey: templatesQueryKey });
  const sessionQuery = useQuery({
    queryFn: getTemplateSession,
    queryKey: [...templatesQueryKey, "session"],
  });
  const configQuery = useQuery({ queryFn: getAppConfig, queryKey: configQueryKey });
  const charactersQuery = useQuery({ queryFn: listCharacters, queryKey: charactersQueryKey });
  const backgroundsQuery = useQuery({ queryFn: listBackgrounds, queryKey: backgroundsQueryKey });
  const effectsQuery = useQuery({ queryFn: listEffects, queryKey: effectsQueryKey });
  const runtimeSnapshotQuery = useQuery({
    queryFn: getChatSnapshot,
    queryKey: [...chatQueryKey, "snapshot", "launch-guard"],
    refetchInterval: 1200,
  });
  const templates = templatesQuery.data ?? [];
  const isLoading = templatesQuery.isLoading;
  const launchSession = sessionQuery.data;
  const sessionFetched = sessionQuery.isFetched;
  const appConfig = configQuery.data;
  const characters = charactersQuery.data ?? [];
  const backgrounds = backgroundsQuery.data ?? [];
  const effects = Array.isArray(effectsQuery.data) ? effectsQuery.data : [];
  const [selectedId, setSelectedId] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [sessionDraftActive, setSessionDraftActive] = useState(false);
  const [sessionRestored, setSessionRestored] = useState(false);
  const [draft, setDraft] = useState<TemplateSummary>(() => createTemplateDraft(t("template.defaultName")));
  const [nameError, setNameError] = useState("");
  const [selectedCharacters, setSelectedCharacters] = useState<string[]>([]);
  const [selectedBackground, setSelectedBackground] = useState(TRANSPARENT_BACKGROUND_NAME);
  const [selectedEffects, setSelectedEffects] = useState<string[]>([]);
  const [voiceLanguage, setVoiceLanguage] = useState("ja");
  const [useEffectPrompt, setUseEffectPrompt] = useState(true);
  const [useTranslation, setUseTranslation] = useState(true);
  const [useCg, setUseCg] = useState(false);
  const [useCot, setUseCot] = useState(false);
  const [useChoice, setUseChoice] = useState(true);
  const [useNarration, setUseNarration] = useState(true);
  const [useStat, setUseStat] = useState(true);
  const [maxSpeechChars, setMaxSpeechChars] = useState(0);
  const [maxDialogItems, setMaxDialogItems] = useState(0);
  const [initSpritePath, setInitSpritePath] = useState("");
  const [historyPath, setHistoryPath] = useState("");
  const [roomId, setRoomId] = useState("");
  const [systemExpanded, setSystemExpanded] = useState(false);
  const [quickRestartOpen, setQuickRestartOpen] = useState(false);
  const localRuntimeClosing = useChatRuntimeClosing();
  const autoGenerateReadyRef = useRef(false);
  const lastAutoGeneratedCharactersRef = useRef("");
  const lastAutoScenarioRef = useRef("");
  const suppressNextAutoGenerateRef = useRef(false);

  const selected = useMemo(
    () => (isCreating ? undefined : (templates.find((template) => template.id === selectedId) ?? templates[0])),
    [isCreating, selectedId, templates],
  );
  const backgroundOptions = useMemo(() => {
    const names = backgrounds.map((background) => background.name);
    return names.includes(TRANSPARENT_BACKGROUND_NAME) ? names : [...names, TRANSPARENT_BACKGROUND_NAME];
  }, [backgrounds]);
  const selectedCharacterNames = useMemo(() => new Set(selectedCharacters), [selectedCharacters]);
  const selectedEffectNames = useMemo(() => new Set(selectedEffects), [selectedEffects]);

  const effectHintText = useMemo(() => {
    if (!selectedEffects.length) return "";
    const lines: string[] = ["可用音效："];
    for (const ef of effects) {
      if (selectedEffectNames.has(ef.name)) {
        const tags = (ef.audio_tags || "").split("\n").filter(Boolean);
        const kws: string[] = [];
        for (const tag of tags) {
          const kw = tag.replace(/^特效\s*\d+\s*[：:]\s*/, "").trim();
          if (kw) kws.push(kw);
        }
        if (kws.length) {
          lines.push(`${ef.name}有${kws.length}条特效音频：`);
          kws.forEach((kw, i) => lines.push(`${i + 1}. ${kw}`));
        }
      }
    }
    if (lines.length <= 1) return "";
    lines.push("");
    lines.push("音效触发时机与模式：");
    lines.push("- before:关键词 → 对话前播放一次");
    lines.push("- after:关键词 → 对话后播放一次");
    lines.push("- loop:关键词 → 开始循环播放（用于持续性音效如雨声、风声）");
    lines.push("- stop:关键词 → 停止循环播放");
    lines.push("- 关键词 → 默认对话前播放一次");
    lines.push('循环示例：开始时 {"effect": "loop:雨声"}，结束时 {"effect": "stop:雨声"}');
    return lines.join("\n");
  }, [effects, selectedEffectNames, selectedEffects]);

  // 选特效后自动写入/更新系统提示词（插在背景和可调用工具之间）
  useEffect(() => {
    setDraft((current) => {
      let sys = current.system ?? "";
      // 先移除旧的音效段落
      const hintIdx = sys.indexOf("可用音效：");
      if (hintIdx !== -1) {
        let endIdx = sys.indexOf("\n\n", hintIdx + 12);
        if (endIdx === -1) endIdx = sys.indexOf("\n", hintIdx + 12);
        if (endIdx === -1) endIdx = sys.length;
        // 向后找连续的空白行
        while (endIdx < sys.length && sys[endIdx] === "\n") endIdx++;
        sys = sys.slice(0, hintIdx) + sys.slice(endIdx);
      }
      if (!effectHintText) {
        if (sys === (current.system ?? "")) return current;
        return { ...current, system: sys };
      }
      // 插入到背景段落后、可调用工具前
      const toolIdx = sys.indexOf("可调用工具");
      if (toolIdx !== -1) {
        // 在可调用工具前插入
        sys = sys.slice(0, toolIdx) + "\n" + effectHintText + "\n\n" + sys.slice(toolIdx);
      } else {
        // 找不到可调用工具，追加到末尾
        sys = sys.trimEnd() + "\n\n" + effectHintText;
      }
      if (sys === (current.system ?? "")) return current;
      return { ...current, system: sys };
    });
  }, [effectHintText]);
  const failedQuery = [templatesQuery, sessionQuery, configQuery, charactersQuery, backgroundsQuery, effectsQuery].find(
    (query) => query.isError,
  );
  const runtimeLaunchDisabled =
    localRuntimeClosing ||
    Boolean(runtimeSnapshotQuery.data?.chatRuntimeClosing || runtimeSnapshotQuery.data?.chatProcessRunning);
  const templateSelectValue = !isCreating && !sessionDraftActive ? selectedId || selected?.id || "" : "";

  useEffect(() => {
    if (selected && !sessionDraftActive) {
      setSelectedId(selected.id);
      setDraft(normalizeTemplateSummary(structuredClone(selected)));
      setNameError("");
    }
  }, [selected, sessionDraftActive]);

  useEffect(() => {
    if (!sessionFetched || sessionRestored) {
      return;
    }
    if (launchSession?.templateFileDropdown && !templates.length) {
      return;
    }
    setSessionRestored(true);
    if (!launchSession) {
      return;
    }
    setSessionDraftActive(true);
    setSelectedCharacters(Array.isArray(launchSession.selectedCharacters) ? launchSession.selectedCharacters : []);
    setSelectedBackground(launchSession.background || TRANSPARENT_BACKGROUND_NAME);
    setSelectedEffects(Array.isArray(launchSession.effectNames) ? launchSession.effectNames : []);
    setVoiceLanguage(launchSession.voiceLanguage || "ja");
    setUseEffectPrompt(launchSession.useEffect ?? true);
    setUseTranslation(launchSession.useTranslation ?? true);
    setUseCg(launchSession.useCg ?? false);
    setUseCot(launchSession.useCot ?? false);
    setUseChoice(launchSession.useChoice ?? true);
    setUseNarration(launchSession.useNarration ?? true);
    setUseStat(launchSession.useStat ?? true);
    setMaxSpeechChars(Number(launchSession.maxSpeechChars) || 0);
    setMaxDialogItems(Number(launchSession.maxDialogItems) || 0);
    setInitSpritePath(launchSession.initSpritePath || "");
    setHistoryPath(launchSession.historyPath || "");
    setRoomId(launchSession.roomId || "");
    const matchingTemplate = templates.find((template) => template.id === launchSession.templateFileDropdown);
    setSelectedId(matchingTemplate?.id ?? "");
    setDraft(
      normalizeTemplateSummary({
        content: composeTemplateContent(launchSession.scenario, launchSession.system),
        id: matchingTemplate?.id ?? "",
        name: launchSession.filenameStub || matchingTemplate?.name || t("template.defaultName"),
        path: matchingTemplate?.path ?? "",
        scenario: launchSession.scenario,
        system: launchSession.system,
        updatedAt: matchingTemplate?.updatedAt ?? "",
      }),
    );
  }, [launchSession, sessionFetched, sessionRestored, t, templates]);

  useEffect(() => {
    if (!backgroundOptions.includes(selectedBackground)) {
      setSelectedBackground(TRANSPARENT_BACKGROUND_NAME);
    }
  }, [backgroundOptions, selectedBackground]);

  useEffect(() => {
    if (!sessionRestored || launchSession) {
      return;
    }
    const configuredLanguage = String(appConfig?.system_config.voice_language || "")
      .trim()
      .toLowerCase();
    const nextLanguage = voiceLanguages.some((option) => option.value === configuredLanguage)
      ? configuredLanguage
      : "ja";
    if (!configuredLanguage || nextLanguage === voiceLanguage) {
      return;
    }
    suppressNextAutoGenerateRef.current = true;
    setVoiceLanguage(nextLanguage);
  }, [appConfig, launchSession, sessionRestored, voiceLanguage]);

  const updateDraft = (patch: Partial<TemplateSummary>) => {
    setDraft((current) => {
      const next = { ...current, ...patch };
      const scenario = String(next.scenario ?? "");
      const system = String(next.system ?? "");
      return { ...next, content: composeTemplateContent(scenario, system) };
    });
  };

  const validateName = () => {
    if (!draft.name.trim()) {
      setNameError(t("template.validation.nameRequired"));
      return false;
    }
    setNameError("");
    return true;
  };

  const templateOptionsState = {
    useCg,
    useChoice,
    useCot,
    useEffect: useEffectPrompt,
    useNarration,
    useStat,
    useTranslation,
  };
  const runtimeOptionsState = {
    historyPath,
    initSpritePath,
    maxDialogItems,
    maxSpeechChars,
    roomId,
    voiceLanguage,
  };
  const selectedCharactersKey = selectedCharacters.join("\n");

  const scenarioForSelectedCharacters = () => {
    const currentScenario = String(draft.scenario ?? "");
    const defaultScenario = buildDefaultTemplateScenario(selectedCharacters, t("template.defaultScenario"));
    if (!defaultScenario) {
      if (currentScenario === lastAutoScenarioRef.current) {
        return "";
      }
      return currentScenario;
    }
    if (!currentScenario.trim() || currentScenario === lastAutoScenarioRef.current) {
      return defaultScenario;
    }
    return currentScenario;
  };

  const handleRuntimeDependencyError = async (snapshot: ChatSnapshot) => {
    const dependencyError = snapshot.runtimeDependencyError;
    if (!dependencyError) {
      return false;
    }
    const shouldInstall = window.confirm(
      t("runtimeDeps.installConfirm", {
        module: dependencyError.moduleName,
        package: dependencyError.packageName,
      }),
    );
    if (!shouldInstall) {
      showToast({ kind: "error", message: snapshot.dialogText, title: t("template.error.launchFailed") });
      return true;
    }
    try {
      const result = await installMissingRuntimeDependency({ moduleName: dependencyError.moduleName });
      showToast({
        kind: "success",
        message: result.message || t("runtimeDeps.installSucceeded"),
        title: t("runtimeDeps.installTitle"),
      });
    } catch (error) {
      showToast({
        kind: "error",
        message: error instanceof Error ? error.message : t("runtimeDeps.installFailed"),
        title: t("runtimeDeps.installFailed"),
      });
    }
    return true;
  };

  const saveMutation = useMutation({
    mutationFn: async () => {
      if (!validateName()) {
        throw new Error(t("template.validation.nameRequired"));
      }
      return saveTemplate(buildTemplateSummary(draft));
    },
    onError(error) {
      showToast({
        kind: "error",
        message: error instanceof Error ? error.message : t("template.error.saveFallback"),
        title: t("common.saveFailed"),
      });
    },
    onSuccess(template) {
      queryClient.invalidateQueries({ queryKey: templatesQueryKey });
      const normalized = normalizeTemplateSummary(template);
      setIsCreating(false);
      setSessionDraftActive(false);
      setDraft(normalized);
      setSelectedId(normalized.id);
      showToast({ kind: "success", title: t("template.toast.saved") });
    },
  });

  const voiceLanguageMutation = useMutation({
    mutationFn: async (language: string) => {
      const config = await getAppConfig();
      return saveSystemConfig({
        ...config.system_config,
        voice_language: language,
      });
    },
    onError(error) {
      showToast({
        kind: "error",
        message: error instanceof Error ? error.message : t("system.error.saveFallback"),
        title: t("common.saveFailed"),
      });
    },
  });

  const generateMutation = useMutation({
    mutationFn: async (options?: { scenario?: string; silent?: boolean }) => {
      const scenario = options?.scenario ?? scenarioForSelectedCharacters();
      return generateTemplate(
        buildTemplateGenerateInput({
          backgroundName: selectedBackground,
          draft: { ...draft, scenario },
          effectNames: selectedEffects,
          options: templateOptionsState,
          runtime: runtimeOptionsState,
          selectedCharacters,
        }),
      );
    },
    onError(error, options) {
      if (options?.silent) {
        return;
      }
      showToast({
        kind: "error",
        message: error instanceof Error ? error.message : t("template.error.generateFallback"),
        title: t("template.error.generateFailed"),
      });
    },
    onSuccess(template, options) {
      const normalized = normalizeTemplateSummary(template);
      setIsCreating(true);
      setSessionDraftActive(true);
      // 自动生成后重新注入音效信息
      let sys = normalized.system ?? "";
      const hintIdx = sys.indexOf("可用音效：");
      if (hintIdx !== -1) {
        let endIdx = sys.indexOf("\n\n", hintIdx + 12);
        if (endIdx === -1) endIdx = sys.indexOf("\n", hintIdx + 12);
        if (endIdx === -1) endIdx = sys.length;
        while (endIdx < sys.length && sys[endIdx] === "\n") endIdx++;
        sys = sys.slice(0, hintIdx) + sys.slice(endIdx);
      }
      if (effectHintText) {
        const toolIdx = sys.indexOf("可调用工具");
        if (toolIdx !== -1) {
          sys = sys.slice(0, toolIdx) + "\n" + effectHintText + "\n\n" + sys.slice(toolIdx);
        } else {
          sys = sys.trimEnd() + "\n\n" + effectHintText;
        }
      }
      normalized.system = sys;
      setDraft(normalized);
      if (!options?.silent) {
        showToast({ kind: "success", message: template.generationMessage, title: t("template.toast.generated") });
      }
    },
  });

  useEffect(() => {
    if (!sessionRestored) {
      return;
    }
    if (!autoGenerateReadyRef.current) {
      autoGenerateReadyRef.current = true;
      return;
    }
    if (suppressNextAutoGenerateRef.current) {
      suppressNextAutoGenerateRef.current = false;
      return;
    }
    if (generateMutation.isPending) {
      return;
    }
    if (selectedCharactersKey === lastAutoGeneratedCharactersRef.current) {
      return;
    }
    lastAutoGeneratedCharactersRef.current = selectedCharactersKey;
    const scenario = scenarioForSelectedCharacters();
    if (scenario !== draft.scenario) {
      lastAutoScenarioRef.current = scenario;
      updateDraft({ scenario });
    }
    const timer = window.setTimeout(() => generateMutation.mutate({ scenario, silent: true }), 160);
    return () => window.clearTimeout(timer);
  }, [
    selectedCharactersKey,
    selectedBackground,
    selectedEffects,
    voiceLanguage,
    useEffectPrompt,
    useTranslation,
    useCg,
    useCot,
    useChoice,
    useNarration,
    useStat,
    maxSpeechChars,
    maxDialogItems,
    sessionRestored,
  ]);

  const launchMutation = useMutation({
    mutationFn: async ({ resetHistory }: { resetHistory: boolean }) => {
      if (runtimeLaunchDisabled) {
        throw new Error(t("launch.runtimeBusy"));
      }
      const template = buildTemplateSummary(draft);
      const session: TemplateLaunchSession = buildTemplateLaunchSession({
        backgroundName: selectedBackground,
        draft,
        effectNames: selectedEffects,
        options: templateOptionsState,
        runtime: runtimeOptionsState,
        selectedCharacters,
        selectedTemplateId: selectedId,
      });
      await saveTemplateSession(session);
      queryClient.setQueryData([...templatesQueryKey, "session"], session);
      const snapshot = await launchChat(
        buildChatLaunchPayload({
          backgroundName: selectedBackground,
          effectNames: selectedEffects,
          resetHistory,
          runtime: runtimeOptionsState,
          selectedCharacters,
          template,
          useCg,
        }),
      );
      return { snapshot, template };
    },
    onError(error) {
      showToast({
        kind: "error",
        message: error instanceof Error ? error.message : t("template.error.launchFailed"),
        title: t("template.error.launchFailed"),
      });
    },
    onSuccess({ snapshot, template }) {
      queryClient.setQueryData([...chatQueryKey, "snapshot", "launch-guard"], snapshot);
      const normalized = normalizeTemplateSummary(template);
      setSessionDraftActive(true);
      setDraft(normalized);
      if (snapshot.runtimeDependencyError) {
        void handleRuntimeDependencyError(snapshot);
        return;
      }
      showToast({
        kind: "success",
        message: snapshot.statusMessage || snapshot.dialogText,
        title: t("template.toast.launched"),
      });
      void showChatSurface({ snapshot });
    },
  });

  const toggleCharacter = (name: string, checked: boolean) => {
    setSelectedCharacters((current) =>
      checked ? [...new Set([...current, name])] : current.filter((item) => item !== name),
    );
  };

  const toggleEffect = (name: string, checked: boolean) => {
    setSelectedEffects((current) =>
      checked ? [...new Set([...current, name])] : current.filter((item) => item !== name),
    );
  };

  const handleTemplateSelect = (nextId: string) => {
    if (!nextId) {
      return;
    }
    setSessionDraftActive(false);
    setIsCreating(false);
    setSelectedId(nextId);
  };

  const handleVoiceLanguageChange = (nextLanguage: string) => {
    if (nextLanguage === voiceLanguage) {
      return;
    }
    setVoiceLanguage(nextLanguage);
    voiceLanguageMutation.mutate(nextLanguage);
  };

  const handleGenerateTemplate = () => {
    if (!selectedBackground) {
      showToast({
        kind: "error",
        message: t("template.validation.backgroundRequired"),
        title: t("template.mode.generate"),
      });
      return;
    }
    if (!selectedCharacters.length) {
      showToast({
        kind: "error",
        message: t("template.validation.charactersRequired"),
        title: t("template.mode.generate"),
      });
      return;
    }
    const scenario = scenarioForSelectedCharacters();
    if (scenario !== draft.scenario) {
      lastAutoScenarioRef.current = scenario;
      updateDraft({ scenario });
    }
    generateMutation.mutate({ scenario, silent: false });
  };

  const templateOptions = [
    { key: "effect", label: t("template.field.useEffect"), setValue: setUseEffectPrompt, value: useEffectPrompt },
    {
      key: "translation",
      label: t("template.field.useTranslation"),
      setValue: setUseTranslation,
      value: useTranslation,
    },
    { key: "cg", label: t("template.field.useCg"), setValue: setUseCg, value: useCg },
    { key: "cot", label: t("template.field.useCot"), setValue: setUseCot, value: useCot },
    { key: "choice", label: t("template.field.useChoice"), setValue: setUseChoice, value: useChoice },
    { key: "narration", label: t("template.field.useNarration"), setValue: setUseNarration, value: useNarration },
    { key: "stat", label: t("template.field.useStat"), setValue: setUseStat, value: useStat },
  ];

  return (
    <div className="page template-page">
      <header className="template-page__topbar">
        <label className="template-topbar-field template-topbar-field--select">
          <span className="template-topbar-field__label">{t("template.section.load")}</span>
          <Select
            disabled={!templates.length}
            onChange={(event) => handleTemplateSelect(event.target.value)}
            value={templateSelectValue}
          >
            <option value="">
              {sessionDraftActive || isCreating ? draft.name || t("template.defaultName") : t("template.section.load")}
            </option>
            {templates.map((template) => (
              <option key={template.id} value={template.id}>
                {template.name}
              </option>
            ))}
          </Select>
        </label>
        <label className="template-topbar-field">
          <span className="template-topbar-field__label">{t("template.field.templateName")}</span>
          <span className="input-group">
            <TextInput
              className={nameError ? "input--error" : ""}
              onChange={(event) => {
                updateDraft({ name: event.target.value });
                if (event.target.value.trim()) {
                  setNameError("");
                }
              }}
              value={draft.name}
            />
            <AsyncButton
              className="template-save-button"
              icon={<Save aria-hidden className="button__icon" />}
              loading={saveMutation.isPending}
              onClick={() => saveMutation.mutate()}
            >
              {t("common.save")}
            </AsyncButton>
          </span>
          {nameError ? <span className="field-error">{nameError}</span> : null}
        </label>
      </header>

      {isLoading || failedQuery || (!templates.length && !failedQuery) ? (
        <div className="template-page__status">
          {isLoading ? <EmptyState title={t("template.loading")} /> : null}
          {failedQuery ? (
            <QueryErrorState
              error={failedQuery.error}
              onRetry={() => void failedQuery.refetch()}
              retryLabel={t("common.retry")}
              title={t("common.operationFailed")}
            />
          ) : null}
          {!isLoading && !failedQuery && !templates.length ? (
            <EmptyState title={t("template.emptyTitle")} body={t("template.emptyBody")} />
          ) : null}
        </div>
      ) : null}

      <div className="template-workbench">
        <section className="template-workbench__main">
          <section className="template-panel template-panel--characters">
            <div className="template-character-picker">
              <div className="template-character-picker__header">
                <span className="template-panel__label">{t("template.field.characters")}</span>
                <Button
                  disabled={!characters.length}
                  icon={<Users aria-hidden className="button__icon" />}
                  onClick={() => setSelectedCharacters(characters.map((character) => character.name))}
                  variant="ghost"
                >
                  {t("template.action.selectAllCharacters")}
                </Button>
              </div>
              <div aria-label={t("template.field.characters")} className="template-character-grid" role="group">
                {characters.map((character) => {
                  const isSelected = selectedCharacterNames.has(character.name);
                  return (
                    <button
                      aria-pressed={isSelected}
                      className={`template-character-card${isSelected ? " template-character-card--selected" : ""}`}
                      key={character.name}
                      onClick={() => toggleCharacter(character.name, !isSelected)}
                      style={getCharacterChipStyle(character.color)}
                      title={character.name}
                      type="button"
                    >
                      <span aria-hidden className="template-character-card__dot" />
                      <span className="template-character-card__name">{character.name}</span>
                    </button>
                  );
                })}
              </div>

              {effects.length > 0 ? (
                <div className="template-effect-section">
                  <span className="template-effect-section__label">{t("template.field.effectName")}</span>
                  <div aria-label={t("template.field.effectName")} className="template-character-grid" role="group">
                    {effects.map((effect) => {
                      const isSelected = selectedEffectNames.has(effect.name);
                      return (
                        <button
                          aria-pressed={isSelected}
                          className={`template-character-card${isSelected ? " template-character-card--selected" : ""}`}
                          key={effect.name}
                          onClick={() => toggleEffect(effect.name, !isSelected)}
                          style={{ "--template-character-color": effect.color || "#5b8def" } as CSSProperties}
                          title={effect.name}
                          type="button"
                        >
                          <span aria-hidden className="template-character-card__dot" />
                          <span className="template-character-card__name">{effect.name}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>
              ) : null}
            </div>
          </section>

          <section className="template-panel template-panel--scenario">
            <label className="template-stack-field">
              <span className="template-panel__label">{t("template.field.scenario")}</span>
              <TextArea
                className="template-scenario-textarea"
                onChange={(event) => updateDraft({ scenario: event.target.value })}
                rows={7}
                value={draft.scenario ?? ""}
              />
            </label>
          </section>

          <section className={`template-panel template-panel--system${systemExpanded ? " is-expanded" : ""}`}>
            <button
              aria-expanded={systemExpanded}
              className="template-system-toggle"
              onClick={() => setSystemExpanded((current) => !current)}
              type="button"
            >
              <span>{t("template.section.system")}</span>
              <span aria-hidden className="section-toggle__indicator" />
            </button>
            {systemExpanded ? (
              <label className="template-stack-field template-stack-field--system">
                <span className="template-panel__label">{t("template.field.system")}</span>
                <TextArea
                  className="template-system-textarea"
                  onChange={(event) => updateDraft({ system: event.target.value })}
                  rows={12}
                  value={draft.system ?? ""}
                />
              </label>
            ) : null}
          </section>
        </section>

        <aside className="template-options-panel">
          <div className="template-options-panel__header">
            <h2 className="template-options-panel__title">{t("template.section.generate")}</h2>
            <AsyncButton
              className="template-generate-button"
              icon={<Sparkles aria-hidden className="button__icon" />}
              loading={generateMutation.isPending}
              onClick={handleGenerateTemplate}
              variant="primary"
            >
              {t("template.mode.generate")}
            </AsyncButton>
          </div>

          <label className="template-side-field">
            <span className="template-side-field__label">{t("template.field.background")}</span>
            <Select onChange={(event) => setSelectedBackground(event.target.value)} value={selectedBackground}>
              {backgroundOptions.map((name) => (
                <option key={name} value={name}>
                  {name === TRANSPARENT_BACKGROUND_NAME ? t("template.transparentBackground") : name}
                </option>
              ))}
            </Select>
          </label>

          <div className="template-side-field">
            <span className="template-side-field__label">{t("template.field.voiceLanguage")}</span>
            <div className="template-language-segments" role="group">
              {voiceLanguages.map((option) => (
                <button
                  aria-pressed={voiceLanguage === option.value}
                  className={`template-language-segment${
                    voiceLanguage === option.value ? " template-language-segment--active" : ""
                  }`}
                  key={option.value}
                  onClick={() => handleVoiceLanguageChange(option.value)}
                  type="button"
                >
                  {t(option.labelKey)}
                </button>
              ))}
            </div>
          </div>

          <p className="template-options-panel__hint">{t("template.optionHelp")}</p>

          <div className="template-option-list">
            {templateOptions.map((option) => (
              <label className="template-toggle-row" key={option.key}>
                <span>{option.label}</span>
                <Switch checked={option.value} onChange={(e) => option.setValue(e.target.checked)} />
              </label>
            ))}
          </div>

          <div className="template-number-grid">
            <label className="template-side-field">
              <span className="template-side-field__label">{t("template.field.maxSpeechChars")}</span>
              <NumberInput
                max={500000}
                min={0}
                onChange={(event) => setMaxSpeechChars(Number.parseInt(event.target.value, 10) || 0)}
                step={10}
                value={maxSpeechChars}
              />
            </label>
            <label className="template-side-field">
              <span className="template-side-field__label">{t("template.field.maxDialogItems")}</span>
              <NumberInput
                max={500}
                min={0}
                onChange={(event) => setMaxDialogItems(Number.parseInt(event.target.value, 10) || 0)}
                value={maxDialogItems}
              />
            </label>
          </div>

          <div className="template-runtime-fields">
            <label className="template-side-field">
              <span className="template-side-field__label">{t("template.field.initSprite")}</span>
              <FilePicker
                acceptedExtensions={[".gif", ".jpeg", ".jpg", ".png", ".webp"]}
                onChange={(event) => setInitSpritePath(event.target.value)}
                onPathChange={setInitSpritePath}
                pickLabel={t("common.chooseFile")}
                pickerTitle={t("template.field.initSprite")}
                readOnly={false}
                value={initSpritePath}
              />
            </label>
            <label className="template-side-field">
              <span className="template-side-field__label">{t("template.field.historyFile")}</span>
              <TextInput onChange={(event) => setHistoryPath(event.target.value)} value={historyPath} />
            </label>
          </div>
        </aside>
      </div>

      <footer className="template-page__footer">
        <AsyncButton
          disabled={runtimeLaunchDisabled}
          icon={<Play aria-hidden className="button__icon" />}
          loading={launchMutation.isPending}
          onClick={() => launchMutation.mutate({ resetHistory: false })}
          variant="primary"
        >
          {t("template.action.launch")}
        </AsyncButton>
        <Button
          disabled={runtimeLaunchDisabled}
          icon={<RotateCw aria-hidden className="button__icon" />}
          onClick={() => setQuickRestartOpen(true)}
          variant="ghost"
        >
          {t("template.action.quickRestart")}
        </Button>
      </footer>

      <AlertDialog
        body={t("template.quickRestart.body")}
        cancelLabel={t("common.cancel")}
        closeLabel={t("common.close")}
        confirmLabel={t("template.action.quickRestart")}
        onCancel={() => setQuickRestartOpen(false)}
        onConfirm={() => {
          setQuickRestartOpen(false);
          launchMutation.mutate({ resetHistory: true });
        }}
        open={quickRestartOpen}
        title={t("template.quickRestart.title")}
      />
    </div>
  );
}
